### ISSUE TITLE
[MongoDB] ByteArray is stored as an Array instead of Binary since 4.9.4

### ISSUE THREAD

**Issue by svilen-todorov** [micronaut-projects/micronaut-data#3165] opened 2024-10-08 08:27 UTC
### Expected Behavior

ByteArray to be stored as Binary data type in Mongo

### Actual Behaviour

Since the 4.9.4 update ByteArray is stored as an array of Ints, which increases the used storage size a lot:

![image](https://github.com/user-attachments/assets/86f14b15-138e-4a9f-9122-287925fa4697)

It could be related to this change: https://github.com/micronaut-projects/micronaut-data/commit/ae81d87fba97c2aa71900da2c1e075f9e484bdc4#diff-57d1783e0cc7b290c77c65415c2f14d4f800bd3b108a3489b4879bd1864c811c

If this is intended as a feature, please suggest a way to get the old behavior back(store a Binary) when using the latest version.

### Steps To Reproduce

1. Create a Mongo Object in 4.9.4
2. Store the object in Mongo
3. Switch to 4.9.3
4. Store the same object in Mongo

### Environment Information

- Operating System: Windows
- JDK Version: Oracle OpenJDK 21.0.2

### Version

4.6.3

**Comment by dstepanov** [comment] 2024-10-08 08:41
Looks like a bug. You can try to annotate it with `BsonRepresentation`

**Comment by svilen-todorov** [comment] 2024-10-09 07:58
Thank you, this solved the issue

**Comment by sdelamo** [comment] 2024-10-09 08:09
@dstepanov @radovanradic I assume this is a regression and we will revert back to the previous behaviour.

**Comment by radovanradic** [comment] 2024-10-09 15:40
Fixed in https://github.com/micronaut-projects/micronaut-data/pull/3168

**Closed as completed by radovanradic** 2024-10-09 15:40 UTC
Labels: type: regression
