### ISSUE TITLE
Dynamic order by not respected with nativeQuery

### ISSUE THREAD

**Issue by cgray9** [micronaut-projects/micronaut-data#2338] opened 2023-06-30 05:00 UTC
### Expected Behavior

The results of the following query should be sorted based on the `order` param

Query
```kotlin
@Query(
    """
    SELECT s.id, s.name, s.date_created as dateCreated, coalesce(count(sub.user_id), 0) as subscriptionCount, coalesce(sum(sub.price), 0) as subscriptionMRR FROM service s
    JOIN plan p ON p.service_id = s.id
    LEFT JOIN subscription sub ON p.id = sub.plan_id
    WHERE s.vendor_id = :vendor
    GROUP BY s.id, s.name, s.date_created
    ORDER BY :orderBy
    """,
    nativeQuery = true
)
fun summaryByVendor(vendor: Vendor, orderBy: String? = "id desc"): List<ServiceSummary>?
```

Logs
```
Hibernate:
        SELECT s.id, s.name, s.date_created as dateCreated, coalesce(count(sub.user_id), 0) as subscriptionCount, coalesce(sum(sub.price), 0) as subscriptionMRR FROM service s
        JOIN plan p ON p.service_id = s.id
        LEFT JOIN subscription sub ON p.id = sub.plan_id
        WHERE s.vendor_id = ?
        GROUP BY s.id, s.name, s.date_created
        ORDER BY ?

00:54:39.493 [default-nioEventLoopGroup-3-3] TRACE o.h.type.descriptor.sql.BasicBinder - binding parameter [1] as [BIGINT] - [2]
00:54:39.493 [default-nioEventLoopGroup-3-3] TRACE o.h.type.descriptor.sql.BasicBinder - binding parameter [2] as [VARCHAR] - [id DESC]
```

### Actual Behaviour

The `ORDER BY` clause is ignored when I pass a variable into it and the results are not sorted correctly

Results
```json
[
    {
        "id": 6,
        "name": "Mow and Blow",
        "dateCreated": "Thu, 15 Jun 2023 20:39:05 EDT",
        "subscriptionCount": 0,
        "subscriptionMRR": 0
    },
    {
        "id": 7,
        "name": "Mow and Blow",
        "dateCreated": "Sun, 25 Jun 2023 15:34:18 EDT",
        "subscriptionCount": 3,
        "subscriptionMRR": 360
    }
]
```

### Steps To Reproduce

1. Create a `nativeQuery=true` `@Query`
2. Pass in a variable for the `GROUP BY` clause

### Environment Information

- Micronaut version: v3.9.4
- OS: macOS 12.6.5 
- Java: openjdk 17.0.5 2022-10-18 LTS

### Version

3.9.4

**Comment by radovanradic** [comment] 2023-06-30 12:35
This doesn't work because order cannot be parametrized, essentially this query is executed (if you turn on show_sql)

```
SELECT s.id, s.name, s.date_created as dateCreated, coalesce(count(sub.user_id), 0) as subscriptionCount, coalesce(sum(sub.price), 0) as subscriptionMRR FROM service s
        JOIN plan p ON p.service_id = s.id
        LEFT JOIN subscription sub ON p.id = sub.plan_id
        WHERE s.vendor_id = 1
        GROUP BY s.id, s.name, s.date_created
        ORDER BY 'id desc'
```
and it should be `ORDER BY id desc`. Since hibernate sets string parameter, then it will produce `ORDER BY 'id desc'` and sort by that string expression (which doesn't mean anything) and not by actual column.

**Comment by cgray9** [comment] 2023-06-30 14:33
Thanks for the quick response and clear explanation! Is there a different approach to achieve the desired outcome where ORDER BY can be set dynamically?

**Comment by radovanradic** [comment] 2023-06-30 14:44
@cgray9 Not possible when using native query. Maybe hibernate query + Pageable (with sort option) or with criteria specification and order.

**Comment by radovanradic** [comment] 2023-07-03 07:02
Don't think sending SQL statement would work with Micronaut. Maybe adding few methods with different orders would work for native query, don't see other option. Or if Micronaut supports native query + Pageable which doesn't currently.

**Comment by radovanradic** [comment] 2023-09-08 07:10
Possibly duplicate of https://github.com/micronaut-projects/micronaut-data/issues/842

**Closed** 2023-10-26 08:49 UTC

**Comment by radovanradic** [comment] 2023-10-26 08:54
We added option to sort native queries by passing `Sort` parameter. Something like this for repository:
```
@Repository
public interface AuthorRepository extends CrudRepository<Author, Long> {
...
@Query(value = "select id as authorId, name as authorName from Author", nativeQuery = true)
List<AuthorDto> getAuthorsByNativeQuery(Sort sort);
...
}
```
then call it using 
```
Sort sort = Sort.of(Sort.Order.desc("authorName"));
List<AuthorDto> authors = authorRepository.getAuthorsByNativeQuery(sort);
```
where sort field parameter can be dynamically set in controller, similar to example in this issue.

**Comment by cgray9** [comment] 2023-10-30 15:37
@radovanradic Amazing! Thanks for the update. I'll test it out!

**Comment by radovanradic** [comment] 2023-10-30 15:38
@cgray9 Ok, just to make sure, it is still in snapshot.
