### ISSUE TITLE
Entity implementation detail compromises metadata regardless Data model supposed to only care about public properties

### ISSUE THREAD

**Issue by soberich** [micronaut-projects/micronaut-data#1362] opened 2022-03-01 18:16 UTC
### Expected Behavior

Type of fields should not affect Data module mapping. Internal private typing concerns Micronaut regardless of public api for pojo is consistent

### Actual Behavior

Private field type is considered by this module and breaks design.
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/25544967/156225352-0d326bb6-49ee-4d37-b2ec-cb92656c67b0.png">

#### ~~EDIT~~
~~BTW, same setup within `@Embeddable` works just fine!~~

### Steps To Reproduce

See repro

### Environment Information

Data 3.3.0-RC1
core 3.3.4

### Example Application

https://github.com/soberich/micronaut-data-1362

### Version

3.3.4

**Comment by dstepanov** [comment] 2022-03-02 07:04
It might be an issue that needs to be solved in Core for `BeanIntrospection` to recognize the getter/setter type

**Comment by soberich** [comment] 2022-03-02 09:56
@dstepanov I was under impression that introspection attempts to **only** know about exposed typing (except reading annotations of cource), like as you said - getters/setters (plus ctors) - if not explicitly instructed otherwise (with `@Introspected(access=FIELD)`). 
Seems kind of limiting. Ok, cool, so it'll be fixed?
BTW, this issue is another version of this one micronaut-projects/micronaut-serialization#146
I figured we fell back in that ticket to "poor design" card, so I just wanted to provide a narrower example. 
It strikes me Micronaut too much concern about internal state. There are quite a few design choices Micronaut enforces, like in this example. As I said the impression was that if access is `METHOD`, then no concern about private fields typing.

**Comment by dstepanov** [comment] 2022-03-02 12:09
I would expect the introspection to choose the getter/setter type, so it might be a bug. If you can reproduce it with a basic `@Introspected` and `BeanIntrospection` then it needs to be fixed in the Core.

**Comment by soberich** [comment] 2022-03-02 13:20
@dstepanov would you guys take a look at it / transfer to `-core` if needed? Or do you want some more repro here? Did this one not work as repro by chance? Just to confirm

**Comment by soberich** [comment] 2022-03-05 18:34
@dstepanov thanks for commenting earlier, what about repro? I hope it's sufficient. It's the matter of portability for us, given a lot of code is written in this way and we migrating.

**Comment by dstepanov** [comment] 2022-03-06 13:48
Going to look into it next week?

**Comment by soberich** [comment] 2022-03-06 20:16
That's just music to my ears, thank you so much! Cheers!

**Comment by dstepanov** [comment] 2022-03-09 06:04
I cannot reproduce it with basic introspection. Can you please add testcontainers in your example?

**Comment by soberich** [comment] 2022-03-13 17:32
@dstepanov I didn't get it. What do you mean by "I cannot reproduce it with basic introspection".

**Comment by dstepanov** [comment] 2022-03-14 06:03
I have tried unsuccessfully to reproduce the problem in Core. To check your example it would be nice to include testcontainers as your test requires postgres, otherwise, I need to spend time to add the dependency and the configuration.

**Comment by soberich** [comment] 2022-03-14 20:53
@dstepanov done
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/25544967/158259512-799d84b6-6b0a-43a5-a010-0e43cb6eb15e.png">

**Comment by soberich** [comment] 2022-03-17 13:04
@dstepanov did it work? just curious. Let me know otherwise, so I can work on repro.

**Comment by dstepanov** [comment] 2022-03-17 14:21
Found a bug in Core

**Comment by dstepanov** [comment] 2022-03-21 04:41
Fixed in Core

**Closed by dstepanov** 2022-03-21 04:41 UTC

**Comment by soberich** [comment] 2022-03-27 20:02
@dstepanov Thanks!

**Comment by soberich** [comment] 2022-03-27 21:51
@dstepanov 
I am getting this now
```console
io.micronaut.data.exceptions.DataAccessException: Cannot convert type [class java.util.ArrayList] with value [[]] to target type: class com.google.common.collect.ImmutableList. Consider defining a TypeConverter bean to handle this case.
	at app//io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.lambda$convertRequired$0(ColumnNameResultSetReader.java:99)
	at java.base@11.0.14.1/java.util.Optional.orElseThrow(Optional.java:408)
	at app//io.micronaut.data.jdbc.mapper.ColumnNameResultSetReader.convertRequired(ColumnNameResultSetReader.java:98)
	at app//io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.readEntity(SqlResultEntityTypeMapper.java:441)
	at app//io.micronaut.data.runtime.mapper.sql.SqlResultEntityTypeMapper.map(SqlResultEntityTypeMapper.java:195)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations$1.tryAdvance(DefaultJdbcRepositoryOperations.java:454)
	at java.base@11.0.14.1/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.base@11.0.14.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.14.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.14.1/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base@11.0.14.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@11.0.14.1/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findAll$6(DefaultJdbcRepositoryOperations.java:527)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$executeRead$18(DefaultJdbcRepositoryOperations.java:705)
	at app//io.micronaut.transaction.support.AbstractSynchronousTransactionManager.executeRead(AbstractSynchronousTransactionManager.java:162)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.executeRead(DefaultJdbcRepositoryOperations.java:705)
	at app//io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findAll(DefaultJdbcRepositoryOperations.java:525)
	at app//io.micronaut.data.runtime.intercept.DefaultFindAllInterceptor.intercept(DefaultFindAllInterceptor.java:51)
	at app//io.micronaut.data.runtime.intercept.DefaultFindAllInterceptor.intercept(DefaultFindAllInterceptor.java:35)
	at app//io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:115)
	at app//io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:76)
	at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at app//io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:138)
	at app//io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at app//com.example.repository.Repo$Intercepted.findAll(Unknown Source)
```

there is also again this bugging  `[[]]` which is reminds be about empty array issue but this is not an array - it's a relation.
maybe because it's empty?
