### ISSUE TITLE
Invalid Object-Relational mapping in OneToMany unidirectional relationship

### ISSUE THREAD

**Issue by alberto-pelosi** [micronaut-projects/micronaut-data#192] opened 2019-10-03 15:32 UTC
I'm on 1.0.0.BUILD-SNAPSHOT, but the problem is also in M2.

I'm using Postgres.

I have two classes, Device and Capability.

A Device can have one or more capabilities.

```
@Entity
@Data
@Introspected
public class Device {

 @OneToMany
 List<Capability> capabilities;
```

In DeviceRepository, findAll is defined as follow:

```
public abstract class DeviceRepository implements CrudRepository<Device, Long> {

  @Join(value = "capabilities", type = Join.Type.LEFT_FETCH)
  public abstract List<Device> findAll();
  
}
```

On db there are a _device_ table, a _capability_ table and a join table  called _device_capability_.

Suppose to have 2 device, associated as follow:

device1 - (d1,c1) - capability1
device1 - (d1,c2) - capability2
device1 - (d1,c3) - capability3

device2 - (d2,c3) - capability3
device2 - (d2,c4) - capability4

Calling findAll on DeviceRepository, at object level, I would expect to have two devices, one with three capabilities, one with two capabilities.

On the contrary I have four device objects, two with one identifier, two with another identifier:

device1 => (capability1, capability2)
device1 => (capability3)

device2 => (capability3)
device2 => (capability4)

The query seems to be correct:

SELECT device_.id,device_.manufacturer_code,device_.description,device_.last_update_date,device_.authentication_id,device_capabilities_.id AS _capabilities_id,device_capabilities_.manufacturer_code AS _capabilities_manufacturer_code,device_capabilities_.description AS _capabilities_description,device_capabilities_.default_value AS _capabilities_default_value,device_capabilities_.last_update_date AS _capabilities_last_update_date,device_capabilities_.capability_type AS _capabilities_capability_type,device_authentication_.id AS _authentication_id,device_authentication_.username AS _authentication_username,device_authentication_.password AS _authentication_password FROM device device_ LEFT JOIN device_capability device_capabilities_device_capability_ ON device_.id=device_capabilities_device_capability_.device_id  LEFT JOIN capability device_capabilities_ ON device_capabilities_device_capability_.capability_id=device_capabilities_.id LEFT JOIN authentication device_authentication_ ON device_.authentication_id=device_authentication_.id

**Comment by alberto-pelosi** [comment] 2019-10-04 08:32
I'm sorry, i'm not sure about this issue. It could be an error of my regressesion test. I close the issue.
Thanks

**Comment by alberto-pelosi** [comment] 2019-10-08 09:06
I reopen the issue because the described behaviour happened again. It seems that if the database does not return results ordered by the logical key of the object (the id of the device, in the example), mapping at object level goes wrong. So the pseudo-random beavhiour depends on the preudo-random order of the records in an unordered query.

**Comment by graemerocher** [comment] 2019-11-08 11:52
Could you provide an example with steps to reproduce? Cannot reproduce this myself.

**Comment by mphouston** [comment] 2019-12-05 17:01
I am not sure if this is related.   I see similar behavior with @Join and ONE_TO_MANY.  When I use @Join with the find() method, it only finds one record from the child table (OrderLine in the example).

The symptoms are different than Alberto found.  I always get a single child record in the find() method.  From my debugging session, I think the record returned will be random (based on DB ordering).  I have not seen any cases when the child list returns more than one row.

Let me know if I need to log this as a new bug.

See the sub-project: https://github.com/mphouston/mn-issues/tree/master/join-issue

./gradlew test 

(Some debugging info, ignore if it makes no sense :).

I looked at SqlResultEntityTypeMapper.readEntity() near line 385. It gets the child records from the result set correctly, one at a time.  It then puts each row in a new list and then sets that in the top-level entity property.  This means each row overlays the previous list entries and you end up with one.

The SQL query looks good.  It returns a join of the parent with all 3 child records.

**Comment by graemerocher** [comment] 2020-01-13 11:01
This is fixed in master

**Closed by graemerocher** 2020-01-13 11:01 UTC
Labels: status: awaiting feedback, status: awaiting validation
