### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by kareemelzayat** [micronaut-projects/micronaut-data#2763] opened 2024-01-30 08:00 UTC
### Expected Behavior

Building dynamic queries via JPA and CoroutineJpaSpecificationExecutore should NOT throw exceptions!

### Actual Behaviour

I get the following exception when building a dynamic query. I am using Micronaut Data JPA, and my `Repository` extends the `CoroutineJpaSpecificationExecutor`.

java.lang.ClassCastException: class org.hibernate.query.sqm.tree.select.SqmSelectStatement cannot be cast to class io.micronaut.data.model.jpa.criteria.impl.QueryResultPersistentEntityCriteriaQuery (org.hibernate.query.sqm.tree.select.SqmSelectStatement and io.micronaut.data.model.jpa.criteria.impl.QueryResultPersistentEntityCriteriaQuery are in unnamed module of loader 'app')
	at io.micronaut.data.runtime.intercept.criteria.AbstractSpecificationInterceptor.buildFind(AbstractSpecificationInterceptor.java:319)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCompletionStage] :
	reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.subscribe(WebMetricsPublisher.java:151)
Error has been observed at the following site(s):
	*__InternalFluxOperator.subscribe ⇢ at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.subscribe(WebMetricsPublisher.java:151)
	*________Mono.fromCompletionStage ⇢ at io.micronaut.http.server.RouteExecutor.fromKotlinCoroutineExecute(RouteExecutor.java:555)
	|_                   Mono.flatMap ⇢ at io.micronaut.http.server.RouteExecutor.fromKotlinCoroutineExecute(RouteExecutor.java:556)
	|_             Mono.switchIfEmpty ⇢ at io.micronaut.http.server.RouteExecutor.fromKotlinCoroutineExecute(RouteExecutor.java:572)
	|_                       Mono.map ⇢ at io.micronaut.http.reactive.execution.ReactorExecutionFlowImpl.map(ReactorExecutionFlowImpl.java:71)
	*____________Mono.deferContextual ⇢ at io.micronaut.http.server.RouteExecutor.callRoute(RouteExecutor.java:461)
	|_                   Mono.flatMap ⇢ at io.micronaut.http.reactive.execution.ReactorExecutionFlowImpl.flatMap(ReactorExecutionFlowImpl.java:59)
Original Stack Trace:
		at io.micronaut.data.runtime.intercept.criteria.AbstractSpecificationInterceptor.buildFind(AbstractSpecificationInterceptor.java:319)
		at io.micronaut.data.runtime.intercept.criteria.AbstractSpecificationInterceptor.preparedQueryForCriteria(AbstractSpecificationInterceptor.java:207)
		at io.micronaut.data.runtime.intercept.criteria.async.AbstractAsyncSpecificationInterceptor.findAllAsync(AbstractAsyncSpecificationInterceptor.java:79)
		at io.micronaut.data.runtime.intercept.criteria.async.FindPageAsyncSpecificationInterceptor.intercept(FindPageAsyncSpecificationInterceptor.java:63)
		at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.interceptCompletionStage(DataIntroductionAdvice.java:94)
		at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:82)
		at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
		at com.uberall.lsus.repository.ScheduledUpdateRepository$Intercepted.findAll(Unknown Source)
		at com.uberall.lsus.repository.ScheduledUpdateRepository.findAll(ScheduledUpdateRepository.kt:61)
		at com.uberall.lsus.service.ScheduledUpdateService.getPageableScheduledUpdateList(ScheduledUpdateService.kt:58)
		at com.uberall.lsus.controller.ScheduledUpdateController.list$suspendImpl(ScheduledUpdateController.kt:91)
		at com.uberall.lsus.controller.ScheduledUpdateController$list$1.invokeSuspend(ScheduledUpdateController.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

### Steps To Reproduce

1- Add the dependency: `implementation("io.micronaut.data:micronaut-data-hibernate-jpa:4.5.0")`
2- Create a repository that implements the `CoroutineJpaSpecificationExecutor`
3- Build an arbitrary dynamic query using `PredicateSpecification` or a `QuerySpecification`
4- Execute the code to run the query
5- Wait for the exception to get thrown

### Version

Micronaut Data 4.5.0

**Comment by radovanradic** [comment] 2024-01-30 11:49
I assume this is caused by recent PR https://github.com/micronaut-projects/micronaut-data/pull/2702 when Micronaut tries to delegate criteria to Hibernate when present on the classpath.

**Comment by kareemelzayat** [comment] 2024-01-30 12:24
I assume so as well 👍

**Comment by kareemelzayat** [comment] 2024-01-30 12:57
@radovanradic I tried to dig a bit deep into the issue, but I cannot seem to understand how the mapping to the `SqmCriteriaNodeBuilder` happens. I assume that's because I am using Micronaut JPA, but then we probably need better structuring of the infrastructure; particularly the `AbstractSpecificationInterceptor`

**Comment by kareemelzayat** [comment] 2024-02-01 10:36
@radovanradic is there a way to prioritize this? It is blocking my team

**Comment by radovanradic** [comment] 2024-02-01 10:39
I am currently assigned to different project with higher priority, sorry.

**Comment by dstepanov** [comment] 2024-02-01 10:48
I will check

**Comment by kareemelzayat** [comment] 2024-02-01 11:15
Thanks a lot team!

**Comment by dstepanov** [comment] 2024-02-01 11:24
@kareemelzayat Why do you use the coroutine repositories with synchronous Hibernate?

**Comment by kareemelzayat** [comment] 2024-02-01 12:51
@dstepanov are you implying that we should use [Hibernate Reactive](https://micronaut-projects.github.io/micronaut-data/latest/guide/#hibernateReactive:~:text=5%20Micronaut%20Data%20Hibernate%20Reactive)?

**Comment by dstepanov** [comment] 2024-02-01 13:26
Well, maybe Hibernate Reactive has its own issues. The best thing would be not to use coroutines in your case.

**Comment by kareemelzayat** [comment] 2024-02-01 14:21
This is undesired. We are building our whole system via coroutines and would like to stay consistent with that. We will be happy to wait until this issue is solved, knowing that it would make our system more consistent and robust and performant.

**Closed** 2024-02-05 12:15 UTC

**Comment by kareemelzayat** [comment] 2024-02-05 17:00
@dstepanov I am still experiencing the same issue when using a `findAll(QuerySpecification or PredicateSpecification): Flow`

Also, the last PR caused the Pagination to stop working. I created the issue here: https://github.com/micronaut-projects/micronaut-data/issues/2780

Can we reopen this bug to address the findAll(): Flow issue as well?
