### ISSUE TITLE
Exception when using Micronaut Transaction

### ISSUE THREAD

**Issue by sidhant92** [micronaut-projects/micronaut-data#2662] opened 2023-11-25 14:26 UTC
### Issue description

Getting the following exception when using transactions with JDBI

`java.lang.AbstractMethodError: Receiver class io.micronaut.data.connection.jdbc.advice.ContextualConnection$Intercepted does not define or inherit an implementation of the resolved method 'abstract java.sql.PreparedStatement prepareStatement(java.lang.String, int)' of interface java.sql.Connection.
	at org.jdbi.v3.core.statement.DefaultStatementBuilder.create(DefaultStatementBuilder.java:53)`

**Comment by sdelamo** [comment] 2023-11-25 14:28
@sidhant92 do you have a sample application which reproduces the issue?

**Comment by sidhant92** [comment] 2023-11-25 14:28
Not currently let me try to build one.

**Comment by sidhant92** [comment] 2023-11-25 17:04
Here is the repo:
https://github.com/sidhant92/micronaut-jdbi

Curl for testing:
`curl --location 'localhost:8080/v1/users' \
--header 'Content-Type: application/json' \
--data '{
    "name": "test",
    "age": 21
}'`

**Comment by sidhant92** [comment] 2023-11-26 07:32
It is basically not working when returning back the autogenerated Id.

`return conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);`

**Comment by radovanradic** [comment] 2023-11-28 17:48
Closing as duplicate of https://github.com/micronaut-projects/micronaut-core/issues/10080 which should be fixed now.

**Closed by radovanradic** 2023-11-28 17:48 UTC
