### ISSUE TITLE
`@Query` doesn't escape reserved keywords

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-data#2872] opened 2024-04-09 13:31 UTC
### Expected Behavior

If a method is annotated with `@Query`, I would expect the query to escape reserved keywords. For example:

```java
@Query("update user set locked=true where id=:id")
void lock(Long id);
```

`user` is a reserved name in PostgreSQL.

### Actual Behaviour

The `user` table is not escaped. Even if you use the following query:

```java
@Query("update \"user\" set locked=true where id=:id")
void lock(Long id);
```

The converted query removes escaping.

### Version

4.6.2

**Comment by sdelamo** [comment] 2024-04-19 05:51
@dstepanov @radovanradic maybe we could create a dictionary of reserved words per dialect

**Comment by dstepanov** [comment] 2024-04-19 10:25
We don't want to parse queries more than we do now (just to replace binding). If you use a custom query, you should be doing escaping; I'm not sure why, in this case, the escaping disappears.

**Comment by dstepanov** [comment] 2024-04-22 12:59
@melix I cannot reproduce your issue https://github.com/micronaut-projects/micronaut-data/pull/2900

**Comment by dstepanov** [comment] 2024-09-09 09:21
Closing it because I cannot reproduce it

**Closed as not planned by dstepanov** 2024-09-09 09:21 UTC
Labels: type: improvement
