### ISSUE TITLE
@DateCreated: Breaking change in micronaut-parent:4.3.2

### ISSUE THREAD

**Issue by roar-skinderviken** [micronaut-projects/micronaut-data#2808] opened 2024-02-25 10:22 UTC
### Expected Behavior

When saving an entity with a field like this
```
    @DateCreated
    @Column(nullable = false)
    var created: ZonedDateTime? = null
```
I expect field to be populated during persistence of instance like it did with MN:4.3.1.

### Actual Behaviour

With MN:4.3.2 in the example application, I get this test-error:
```
DemoRepositoryTest » PropertyValue not-null property references a null or transient value : no.javatec.demo.repository.DemoEntity.created
```

### Steps To Reproduce

In the example-app, bump micronaut-parent from 4.3.1 to 4.3.2 or 4.3.3 and run
```
./mvnw clean verify
```
and observe that tests in DemoRepositoryTest are now failing. 

### Environment Information

Ubuntu 22.04
JDK 17
Kotlin 1.9.22

### Example Application

https://github.com/roar-skinderviken/postgres-testcontainer-demo

### Version

4.3.3

**Comment by jamesdh** [comment] 2024-02-28 17:51
I previously reported this in #2342. I was unaware that it was ever working correctly. I'm currently using 4.2.4 and still experience this.

**Comment by radovanradic** [comment] 2024-02-28 20:06
This one is indeed different issue and is caused by micronaut-sql 5.5.1 release. The workaround for this is either adding `implementation("io.micronaut.validation:micronaut-validation")` dependency or adding this JPA property `jpa.default.properties.hibernate.check_nullability=false` but probably should fix root cause in micronaut-sql

**Comment by sdelamo** [comment] 2024-03-14 10:54
@roar-skinderviken I have verified this is solved with 4.3.5

**Comment by roar-skinderviken** [comment] 2024-03-16 17:59
Hi @sdelamo

Build for this PR created by Dependabot for bumping to MN:4.3.5 fails with the same error:
https://github.com/roar-skinderviken/postgres-testcontainer-demo/pull/45

But I can see that 4.3.6 is mentioned above, so maybe wait for that one.

**Comment by roar-skinderviken** [comment] 2024-03-17 11:06
Hi again @sdelamo

Tests are not passing with MN:4.3.6. Could you please describe how you made tests in the example repo passing with MN:4.3.5?

**Comment by sdelamo** [comment] 2024-03-18 17:47
sorry, I had in your sample project both version updated to `4.3.6` and adding the dependency: 

```xml
        <dependency>
            <groupId>io.micronaut.validation</groupId>
            <artifactId>micronaut-validation</artifactId>
        </dependency>
```
and that make it work.

**Comment by timyates** [comment] 2024-03-25 08:46
So micronaut-sql 5.5.2 reverts this change, and it will be in the next 4.3.x release of Micronaut ([4.3.8](https://github.com/micronaut-projects/micronaut-platform/pull/1355))

Thanks @roar-skinderviken for the report!

**Closed by timyates** 2024-03-25 08:46 UTC
Labels: info: workaround available, type: bug
