### ISSUE TITLE
Lombok: non-existent property: id with abstract inheritance

### ISSUE THREAD

**Issue by jonhkr** [micronaut-projects/micronaut-data#126] opened 2019-08-31 13:53 UTC
This error happens when the entities extend a base entity. For example:

```Java
@Data
@MappedSuperclass
abstract class BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @CreationTimestamp
    private Instant createdAt;

    @UpdateTimestamp
    private Instant updatedAt;
}

@Data
@Entity
@Table(name = "customer")
@EqualsAndHashCode(callSuper = true)
public class Customer extends BaseEntity {

    @Version
    private int version;

}

@Repository
interface CustomerRepository extends CrudRepository<Customer, Long> {
}
```

**Comment by graemerocher** [comment] 2019-09-04 14:15
Appears to be lombok related. Works fine when Lombok is not involved. How have you defined Lombok in your build?

**Comment by jonhkr** [comment] 2019-09-06 22:35
I've just added it as a compileOnly and annotationProcessor.

**Comment by graemerocher** [comment] 2019-09-07 08:18
Yes but the order is the processors is important please supply your build

**Comment by jonhkr** [comment] 2019-09-08 01:20
Ok, I'll have to create a demo project since the project that had the issue is now using Spring and the build was changed and not versioned.

I remember that when I moved the properties from the `BaseEntity` to the `Customer` entity and removed the `extends ..` it worked.

I'll work on that demo project and let you know.

**Comment by graemerocher** [comment] 2019-09-10 09:55
Closing for now as cannot reproduce, if you attach an example will reopen

**Comment by orbfish** [comment] 2019-11-18 17:08
@graemerocher I'm seeing this happen also - I changed the buildfile as you suggest, still had the problem, then suddenly *didn't* have the problem. Added another entity, had the problem again, now I can't shake it.

This might be something in IntelliJ, able to start up on the command line. Have you heard of any issues? Or do you have any advice. I use Lombok all the time in our production projects, trying to do a quick prototype to demonstrate how easy it might be to port our existing SpringBoot projects over to Micronaut.

**Comment by graemerocher** [comment] 2019-11-18 18:12
If you provide a reproducer we can take a look

**Comment by outersky** [comment] 2020-02-03 08:51
I encounter this without Lombok, [demo kotlin project](https://github.com/outersky/micronaut-data-bug-mappedsuperclass)

```
Caused by: io.micronaut.data.exceptions.MappingException: Unable to create table column for property [name] of entity [demo.BaseEntity] with unknown data type: OBJECT
	at io.micronaut.data.model.query.builder.sql.SqlQueryBuilder.addTypeToColumn(SqlQueryBuilder.java:1308)
	at io.micronaut.data.model.query.builder.sql.SqlQueryBuilder.buildCreateTableStatements(SqlQueryBuilder.java:315)
	at io.micronaut.data.jdbc.config.SchemaGenerator.createSchema(SchemaGenerator.java:140)
	at io.micronaut.data.jdbc.config.$SchemaGeneratorDefinition.initialize(Unknown Source)
	at io.micronaut.data.jdbc.config.$SchemaGeneratorDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
	... 9 common frames omitted
```

**Comment by outersky** [comment] 2020-02-06 06:15
@graemerocher Would you please have a look at this, thank you.

**Comment by graemerocher** [comment] 2020-02-19 07:32
Thanks for the contribution!

**Closed by graemerocher** 2020-02-19 07:32 UTC
Labels: closed: cannot reproduce, type: bug

**Comment by cloudmisst** [comment] 2024-12-25 08:17
我也是这个错误
