### ISSUE TITLE
Entity's @Where is ignored when repository also has @Where

### ISSUE THREAD

**Issue by sNakahodo** [micronaut-projects/micronaut-data#1300] opened 2022-01-27 00:52 UTC
I have this implementation in my project, for soft delete purpose:

```
@MappedEntity(value = "mytable")
@Where("@.deleted = false")
public abstract class MyEntity {
...
}
```

which is working as expected,  `WHERE deleted = false` is always added to all queries.

However, when I implement this in repository:

```
@Repository
public abstract class MyRepository extends CrudRepository<MyEntity, Long> {
...

    public abstract Optional<MyEntity> findById(Long id);

    // retrieves soft deleted entity for test purpose
    @Where("@.deleted = true")
    public abstract Optional<MyEntity> retrieveById(Long id);

...
}
```

`retrieveById` returns soft deleted record, but weirdly `findById` also returns soft deleted record - it seems to lose MyEntity's effect of `@Where("@.deleted = false")` annotation.

Is it not recommended to have two `@Where` at multiple levels, or would it be an issue with annotation processing?

### Environment Information

- **Operating System**: MacOS BigSur
- **Micronaut Version:** 3.2.4
- **Micronaut Data Version:** 3.1.2
- **JDK Version:** OpenJDK 16

**Comment by dstepanov** [comment] 2022-01-27 08:13
I think it's by design. We do have test `WhereAnnotationSpec` which tests that `@Where` on the entity is removed.

**Comment by sNakahodo** [comment] 2022-01-29 05:49
Thanks @dstepanov 

I did more digging, it looks like the issue is somewhere else because removing `retrieveById` from repository did not resolve the issue.

To be more exact with my implementation, entities are structured as:

```
@Introspected
@Where("@.deleted = false")
public abstract class SoftDeletableEntity {
...
}
```

```
@MappedEntity(value = "mytable1")
public abstract class MyEntity1 extends SoftDeletableEntity {
...
}
```

```
@MappedEntity(value = "mytable2")
public abstract class MyEntity2 extends SoftDeletableEntity {
...
}
```

And each entity has its own repository implementation (MyRepository1 and MyRepository2), and interestingly MyRepository1's `findById` does not return soft deleted MyEntity1, but MyRepository2's `findById` returns soft deleted MyEntity2. 

I saw this issue is resolved when I put `@Where("@.deleted = false")` to each entity instead of the parent SoftDeletableEntity, but I want to avoid this to make the code cleaner - unless the annotation is intentionally designed this way.

**Comment by dstepanov** [comment] 2022-01-31 10:23
Not really sure I understand why would one entity apply the where and another does not. Maybe you can add a test case in `WhereAnnotationSpec` so it can be fixed?

**Comment by barnettj** [comment] 2022-02-01 22:36
Created a reproducible repository here https://github.com/barnettj/micronaut-data-annotation-repro.

Person represents the setup with an @Join. 
Car represents the scenario where there is no join on the repository operation.

Our expectation is that the test `shouldNotRetrieveDeletedPerson` should not return any result.

It seems strange to me that the @Where criteria on the entity would be removed because there is a join defined at the repository level. Why would the criteria not concatenate?

**Comment by barnettj** [comment] 2022-02-01 22:55
The generated query:
```
Executing Query: SELECT person_."id",person_."deleted",person_person_information_."id" AS person_information_id,person_person_information_."person_id" AS person_information_person_id FROM "person" person_ LEFT JOIN "person_information" person_person_information_ ON person_."id"=person_person_information_."person_id" WHERE (person_."id" = ?)
```

**Comment by barnettj** [comment] 2022-02-09 22:09
@dstepanov do you know if this is expected behaviour? If it is, we can just probably close this issue.

Would be valuable as extra doco either way.

**Comment by dstepanov** [comment] 2022-02-11 07:28
@barnettj I see the problem but after removing `@Repository` and leaving only `@JdbcRepository` tests pass.

**Comment by radovanradic** [comment] 2023-09-28 08:47
This appears to be fixed now in Micronaut 4.x (at least this repro from @barnettj) as there were some issues fixed related to where annotation. 
In case you still see the issue please reopen with the reproducer.

**Closed by radovanradic** 2023-09-28 08:47 UTC
