### ISSUE TITLE
DOCS request: add info about joins using Micronaut data-JDBC

### ISSUE THREAD

**Issue by ArthurHarkivsky** [micronaut-projects/micronaut-data#2611] opened 2023-11-07 08:02 UTC
### Issue description

DOCS request: add info about joins using Micronaut data-JDBC
Please.

Make it greater. :-)

**Comment by wetted** [comment] 2023-11-15 20:38
duplicate of #2618. We'll do a PR off that issue.

**Closed by wetted** 2023-11-15 20:38 UTC
Labels: type: docs
