### ISSUE TITLE
Error performing query findByProperty being property a Bean

### ISSUE THREAD

**Issue by ramiroeruiz** [micronaut-projects/micronaut-data#1674] opened 2022-08-01 18:38 UTC
### Expected Behavior

I come across a runtime error when calling a method from a repository
When performing a query findByProperty I get the error, but if I perform a query findByAssociationProperty, then it works fine. Apparently this error started occuring since a version update

In the example, **backpackRepository.findByStudentName** works fine, but **backpackRepository.findByStudent** throws an error
```
    @Test
    public void doTestStudentBackpackQuery() {

        Student student = studentRepository.findByName(studentName).get();

        Optional<Backpack> optDc1 = Assertions.assertDoesNotThrow(() -> backpackRepository.findByStudentName(student.getName()));
        log.debug("found backpack via student name {}", optDc1.isPresent());

        Optional<Backpack> optDc = Assertions.assertDoesNotThrow(() -> backpackRepository.findByStudent(student));
        log.debug("found backpack via student bean {}", optDc.isPresent());
    }
```

### Actual Behaviour

when performing a findByProperty query, it is throwing an error
_SqlExceptionHelper - could not extract ResultSet [n/a]
org.postgresql.util.PSQLException: No value has been specified for parameter 2_

### Steps To Reproduce

In repo https://github.com/ramiroeruiz/mnatPrepersistPoc
Run test class **StudentTest**
Method doTestStudentBackpackQuery throws an error in the second assert
- Optional<Backpack> optDc = Assertions.assertDoesNotThrow(() -> backpackRepository.findByStudent(student));

Before upgrading micronaut, this was working fine. Perhaps there is something new I am missing

Another thing to point out is, this works fine if the expected result is a List or any other Iterable. It fails when a "LIMIT 1" is needed

### Environment Information

- SO Ubuntu 20.04
- JDK 17.0.2

### Example Application

https://github.com/ramiroeruiz/mnatPrepersistPoc

### Version

3.5.3

**Comment by radovanradic** [comment] 2022-08-15 13:44
I looked at this issue and it appears this issue is reproducible in Hibernate with similar use case. Here is [small project](https://github.com/radovanradic/hibernate-example-one2one-bug) reproducing the error in Hibernate. This might be some edge case which Hibernate developers didn't expect to be used because to get Backpack in this case you could just use student.getBackpack without going to the repository. I understand this is not the point of this issue and bug definitely exists but it is on Hibernate end. It happens in OneToOne relation find where setMaxResults(int) is applied to the query. They set parameter (Student) but don't move pointer/index for next parameter which is limit parameter from setMaxResults because of https://github.com/hibernate/hibernate-orm/blob/5.6/hibernate-core/src/main/java/org/hibernate/type/OneToOneType.java#L117 which is being called from org.hibernate.loader.Loader 
```
protected final PreparedStatement bindPreparedStatement(
			final PreparedStatement st,
			final QueryParameters queryParameters,
			final LimitHandler limitHandler,
			final SharedSessionContractImplementor session) throws SQLException, HibernateException {

		final Dialect dialect = getFactory().getDialect();
		final RowSelection selection = queryParameters.getRowSelection();
		final boolean callable = queryParameters.isCallable();

		try {

			int col = 1;
			//TODO: can we limit stored procedures ?!
			col += limitHandler.bindLimitParametersAtStartOfQuery( selection, st, col );

			if ( callable ) {
				col = dialect.registerResultSetOutParameter( (CallableStatement) st, col );
			}

            // This does not move next index when param is OneToOne 
			col += bindParameterValues( st, queryParameters, col, session );
```

Interestingly enough, this error is not reproducible in Hibernate 6.1.2 as you can see in this [example](https://github.com/radovanradic/hibernate-example-one2one-working). So the issue should be gone once we move to latest Hibernate version. Not sure when this will happen but I assume @dstepanov micronaut team is not going to work on fixing this issue?

**Comment by dstepanov** [comment] 2022-08-15 14:27
Not sure how did it work before? It's possible we were setting the id instead of the entity, or Hibernate broke it. Anyway, the solution would be to wait for the Hibernate 6 when we support it.

**Comment by radovanradic** [comment] 2022-08-15 14:45
Maybe there was different Hibernate version and the issue is introduced in 5.6.xm of Hibernate, but that is unlikely. Change to Hibernate 6 would assume quite a lot of refactoring in Micronaut since they are using different packages and there will be also some incompatibilities in the API.

**Comment by radovanradic** [comment] 2023-07-14 12:57
Fixed in Micronaut 4.

**Closed by radovanradic** 2023-07-14 12:57 UTC
Labels: type: bug
