### ISSUE TITLE
Returned Page number incorrect

### ISSUE THREAD

**Issue by FrogDevelopper** [micronaut-projects/micronaut-data#3172] opened 2024-10-11 09:30 UTC
### Expected Behavior

In version 4.9.4, when returning a `Page` in a HTTP REST endpoint, the `pageable.number` value is correct

### Actual Behaviour

The `pageable.number` is `0`

### Steps To Reproduce

1. Checkout example repository https://github.com/FrogDevelopper/micronaut-4_5
2. Switch to branch **example/4_6**
3. Run tests in `MyControllerTest` => all pass ✅ 
4. Upgrade micronautVersion to **4.6.3** in _gradle.properties_ file
5. Run tests in MyControllerTest` => test with page number fails ❌ 

### Environment Information

JDK Version: 21

### Example Application

https://github.com/FrogDevelopper/micronaut-4_5

### Version

4.6.3

**Comment by radovanradic** [comment] 2024-10-11 09:42
Could be regression caused by this https://github.com/micronaut-projects/micronaut-data/pull/3142

**Comment by radovanradic** [comment] 2024-10-11 10:09
@FrogDevelopper Sorry, can't find branch `example/4_6` in your repository to reproduce issue. Have you deleted it in the meantime?

**Comment by FrogDevelopper** [comment] 2024-10-11 10:10
ha, sorry, my push failed

**Comment by FrogDevelopper** [comment] 2024-10-11 10:10
@radovanradic it should be good now

**Comment by radovanradic** [comment] 2024-10-11 13:20
Fixed in https://github.com/micronaut-projects/micronaut-data/pull/3173

**Closed as completed** 2024-10-11 13:20 UTC
Labels: type: bug
